[package]
name = "sentinel1_denoise"
version = "0.1.0"
authors = ["PeterQLee <leep1995@gmail.com>"]
edition = "2018"

[dependencies]
openblas-src = "0.5"
quick-xml = "0.14.0"
ndarray = "0.12.1"
ndarray-linalg = "0.11.1"
ndarray-parallel = "0.9.1"
rayon = "1.2.1"
time = "*"
hdf5 = "0.5.1"
zip = "0.5.3"

[lib]
name = "denoise_engine"
path = "src/lib.rs"

[[bin]]
name = "quickrun"
path = "src/quickrun.rs"

[[bin]]
name = "noise_to_tiff"
path = "src/noise_to_tiff.rs"